name: Deploy Blazor WASM to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Update as needed

      # 3. Publish the Blazor WASM app to the 'release' folder
      - name: Publish Blazor WebAssembly app
        run: dotnet publish -c Release -o release

      # 4. Copy index.html to 404.html for SPA fallback on GitHub Pages
      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # 5. Upload the 'wwwroot' folder contents (the published site)
      - name: Upload artifact (only wwwroot)
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
